--------------------------------------------------------
--  DDL for Table GROUVEE_IMPORT
--------------------------------------------------------

CREATE TABLE "GAMETRACKER"."GROUVEE_IMPORT"
 (	"ID" NUMBER(13,0),
"NAME" VARCHAR2(128 CHAR),
"SHELVES" VARCHAR2(4000 CHAR),
"PLATFORMS" VARCHAR2(4000 CHAR),
"RATING" NUMBER(1,0),
"REVIEW" VARCHAR2(4000 CHAR),
"DATES" VARCHAR2(4000 CHAR),
"STATUSES" VARCHAR2(4000 CHAR),
"GENRES" VARCHAR2(4000 CHAR),
"FRANCHISES" VARCHAR2(4000 CHAR),
"DEVELOPERS" VARCHAR2(4000 CHAR),
"PUBLISHERS" VARCHAR2(4000 CHAR),
"RELEASE_DATE" VARCHAR2(15 CHAR),
"URL" VARCHAR2(4000 CHAR),
"GIANTBOMB_ID" NUMBER(13,0)
 ) ;

ALTER TABLE "GAMETRACKER"."GROUVEE_IMPORT" MODIFY ("ID" NOT NULL ENABLE);
ALTER TABLE "GAMETRACKER"."GROUVEE_IMPORT" MODIFY ("NAME" NOT NULL ENABLE);
