--------------------------------------------------------
--  DDL for Table GENRE_LIST
--------------------------------------------------------

CREATE TABLE GAMETRACKER.GENRE_LIST
 (	GAME_ID NUMBER(13) NOT NULL,
    GENRE_ID NUMBER(13) NOT NULL,
    LAST_UPDATED TIMESTAMP  DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT GENRE_LIST_PK PRIMARY KEY (GAME_ID, GENRE_ID),
    CONSTRAINT GAMEGENRE_FK FOREIGN KEY (GAME_ID) REFERENCES GAMES (ID),
    CONSTRAINT GENRE_FK FOREIGN KEY (GENRE_ID) REFERENCES GENRES (ID)
) ORGANIZATION INDEX;

CREATE INDEX GENRE_LIST_IX ON GENRE_LIST(GENRE_ID);
