--------------------------------------------------------
--  DDL for Table SHELF_LIST
--------------------------------------------------------

CREATE TABLE GAMETRACKER.SHELF_LIST
 (	GAME_ID NUMBER(13) NOT NULL,
    SHELF_ID NUMBER(13) NOT NULL,
    DATE_ADDED DATE,
    LAST_UPDATED TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT SHELFLIST_PK PRIMARY KEY (GAME_ID, SHELF_ID),
    CONSTRAINT GAMESHELF_FK FOREIGN KEY (GAME_ID) REFERENCES GAMES (ID),
    CONSTRAINT SHELF_FK FOREIGN KEY (SHELF_ID) REFERENCES SHELVES(ID)
) ORGANIZATION INDEX;

CREATE INDEX SHELF_LIST_IX ON SHELF_LIST(SHELF_ID);
