--------------------------------------------------------
--  DDL for Table GAMES_JSON
--------------------------------------------------------

CREATE TABLE GAMETRACKER.GAMES_JSON
 (	ID NUMBER(13) GENERATED ALWAYS AS IDENTITY,
    NAME VARCHAR2(128 CHAR) NOT NULL ENABLE,
    SHELVES CLOB,
    PLATFORMS CLOB,
    RATING NUMBER(1,0),
    REVIEW CLOB,
    DATES CLOB,
    GENRES CLOB,
    FRANCHISES CLOB,
    DEVELOPERS CLOB,
    PUBLISHERS CLOB,
    RELEASE_DATE DATE,
    GROUVEE_URL VARCHAR2(2048 CHAR),
    GIANTBOMB_ID NUMBER(13,0),
    LAST_UPDATED TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT GAMES_JSON_PK PRIMARY KEY (ID),
    CONSTRAINT SHELVES_JSON CHECK (SHELVES IS JSON (STRICT)),
    CONSTRAINT PLATFORMS_JSON CHECK (PLATFORMS IS JSON (STRICT)),
    CONSTRAINT DATES_JSON CHECK (DATES IS JSON (STRICT)),
    CONSTRAINT GENRES_JSON CHECK (GENRES IS JSON (STRICT)),
    CONSTRAINT FRANCHISES_JSON CHECK (FRANCHISES IS JSON (STRICT)),
    CONSTRAINT DEVELOPERS_JSON CHECK (DEVELOPERS IS JSON (STRICT)),
    CONSTRAINT PUBLISHERS_JSON CHECK (PUBLISHERS IS JSON (STRICT))
);
