-- Change to PDB which was created inside parent iamge
ALTER SESSION SET CONTAINER = FREEPDB1;

-- Create table space for demo application
DECLARE
  v_ts_id V$TABLESPACE.TS#%TYPE;
BEGIN
  SELECT TS# into v_ts_id FROM V$TABLESPACE WHERE name = 'GURANTS';
EXCEPTION
  WHEN no_data_found THEN
    EXECUTE IMMEDIATE
      'CREATE SMALLFILE TABLESPACE "GAMETRACKER" ' ||
      '  DATAFILE ''/opt/oracle/oradata/FREE/FREEPDB1/gametracker-1.dbf'' SIZE 16M AUTOEXTEND ON NEXT 16M MAXSIZE 1024M ' ||
      '  LOGGING ' ||
      '  DEFAULT NOCOMPRESS ' ||
      '  ONLINE ' ||
      '  EXTENT MANAGEMENT LOCAL AUTOALLOCATE ' ||
      '  SEGMENT SPACE MANAGEMENT AUTO';
END;
/

-- Create user:
DECLARE
  v_id DBA_USERS.USER_ID%TYPE;
BEGIN
  SELECT USER_ID INTO v_id FROM DBA_USERS WHERE username = 'GAMETRACKER';
EXCEPTION
  WHEN no_data_found THEN
    EXECUTE IMMEDIATE
      'CREATE USER gametracker IDENTIFIED BY gametracker PROFILE "DEFAULT" ACCOUNT UNLOCK DEFAULT TABLESPACE  "GAMETRACKER" TEMPORARY TABLESPACE "TEMP"';
END;
/

GRANT "CONNECT" TO gametracker;
GRANT "DBA" TO gametracker;

EXIT;
